# Generated by Django 6.0.5 on 2026-10-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_people_project_amount_collected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Blocked', 'Blocked'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
