# Generated by Django 6.0.5 on 2026-10-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_task_taskattachment_taskcomment_taskdailyupdate_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='department',
            name='department_valid_name',
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('HR', 'HR'), ('IT', 'IT'), ('Marketing', 'Marketing'), ('Manager', 'Manager')], max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(condition=models.Q(('name__in', ['HR', 'IT', 'Marketing', 'Manager'])), name='department_valid_name'),
        ),
    ]
