# Generated by Django 6.0.4 on 2026-05-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='meeting_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
