# Generated by Django 6.0.5 on 2026-10-04 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_delete_attendance'),
        ('dashboard', '0003_alter_schedule_options_alter_schedule_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='student',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
